spring:
  application:
    name: musicapp
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  docker:
    compose:
      enabled: false
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5433}/${DB_NAME:SoundCloudDB}?sslmode=${DB_SSLMODE:disable}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:app_user}
    password: ${DB_PASSWORD:app_user_1412}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:redis123}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 5000
      "[mail.smtp.writetimeout]": 5000

jwt:
  secret: ${JWT_SECRET:change-this-in-production-at-least-32-characters}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}

aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:amzn-s3-bucket-soundstorage}
    region: ${AWS_REGION:ap-southeast-1}
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}

# Cho phép truy cập các endpoint Actuator từ bên ngoài
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus # Docker/K8s dùng health, Prometheus dùng metrics
  endpoint:
    health:
      show-details: always # Hiển thị chi tiết trạng thái DB, Redis, Disk...

  prometheus:
    metrics:
      export:
        enabled: true  # Xuất metrics cho Prometheus/Grafana