name: CI Frontend Pipline

on: 
    push: 
        branches: 
            - "**"
        paths: 
            - "MusicApp_FE/**"
            - ".github/workflows/pipline-frontend.yml"
    pull_request: 
        branches: 
            - "main"
        paths: 
            - "MusicApp_FE/**"

concurrency:
  group: ci-frontend
  cancel-in-progress: true

jobs: 
    build: 
        runs-on: ubuntu-latest
        defaults: 
            run: 
                working-directory: ./MusicApp_FE
        permissions: 
            actions: read
            contents: read
            security-events: write

        steps: 
            - name: Checkout code 
              uses: actions/checkout@v4
            
            - name: Set up Node.js 
              uses: actions/setup-node@v4
              with: 
                node-version: '24'
                cache: 'npm'
                cache-dependency-path: MusicApp_FE/package-lock.json

            - name: Install dependencies 
              run: npm install

            - name: lint
              run: npm run lint

           # - name: Unit test
           #   run: npm run test

            - name: Build application
              run: npm run build

            - name: security scan
              run: npm audit
              continue-on-error: true

            - uses: actions/upload-artifact@v4
              with:
                name: frontend-dist
                path: MusicApp_FE/dist

    deploy: 
        runs-on: ubuntu-latest
        permissions:
          id-token: write
          contents: read
        needs: build
        # Chỉ chạy Job deploy nếu code nằm trên nhánh main
        if: github.ref == 'refs/heads/main'   
        defaults: 
            run: 
                working-directory: ./MusicApp_FE

        steps: 
            - name: down-artifact
              uses: actions/download-artifact@v4
              with: 
                name: frontend-dist
                path: MusicApp_FE/dist

            # Login AWS bằng OIDC
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::587861287952:role/GitHubActions-S3DeployRole
                aws-region: ${{secrets.AWS_REGION}}
            
            - name: Deploy to S3 
              run: | 
                aws s3 sync ./dist s3://${{secrets.MUSIC_APP_FRONTEND_BUCKET}} --delete
            
            - name: Invalidate CloudFront
              run: |
                aws cloudfront create-invalidation \
                    --distribution-id ${{secrets.CLOUDFRONT_DISTRIBUTION_ID}} \
                    --paths "/*"
            